name: ci

on: [push, pull_request]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.3
          cache: npm
      - run: npm ci
      - run: npm run lint-raw

  karma:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.3
          cache: npm
      - run: npm ci
      - run: npx run-s bundle test-unit-karma

  promises-and-observables:
    strategy:
      matrix:
        node:
          - 16.13
          - 18.12
          - 20.3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npx run-s test-promises test-observables

  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        node:
          - 16.13
          - 18.12
          - 20.3
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npx run-s bundle test-unit-node test-entries test-compat-data test-compat-tools test-builder
